exp_name: cyclegan_day2night

data:
  day_dir: data/night2day/night_to_day/trainA
  night_dir: data/night2day/night_to_day/trainB
  extensions: ["jpg", "jpeg", "png"]
  sample_limit: 1000

transforms:
  resize: 256
  random_crop: 512
  center_crop: 512
  random_flip: true

model:
  generator:
    in_channels: 3
    out_channels: 3
    base_channels: 64
    n_res_blocks: 9
    use_skip: true
    encoder_checkpoint: experiments/seg_cityscapes_1k_encoder_GE.pth
    freeze_encoder: true
    decoder_res_blocks: 3
  discriminator:
    in_channels: 3
    base_channels: 64
    n_layers: 3
    max_channels: 512

loss:
  lambda_cycle: 10.0
  lambda_identity: 5.0

optim:
  generator:
    lr: 2.0e-4
    betas: [0.5, 0.999]
  discriminator:
    lr: 2.0e-4
    betas: [0.5, 0.999]

train:
  epochs: 200
  batch_size: 1
  workers: 4
  seed: 42
  lr_decay_start: 100
  amp: true

logging:
  out_dir: experiments
  results_dir: results
  save_every: 10
  log_interval: 100
